# Generated by Django 5.1.7 on 2025-05-12 05:52

import myapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250512_1051'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', myapp.models.CustomUserManager()),
            ],
        ),
    ]
